name: test-clang-format

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.17
      with:
        source: './src'
        extensions: 'c,h'
        clangFormatVersion: 17
